on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

name: publish package
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - run: curl https://proxy.golang.org/github.com/ninedraft/gemax/@v/${{ github.ref }}.info
